### ISSUE TITLE
Bug (Movement keys messed,unusual character,movement speed)

### ISSUE THREAD

**Issue by Andy6575** [SleepingTea98/Infinity-Modpack#1]
Hi, I usually play kinetic infinity on my friend's private server but today when I logged in, my character appears to be a total mess. Apologies in advance about the quality of the videos, I just installed fraps and I really don't know how it works. Hopefully, you guys can still see it. 
Bugs: Texture&screen tearing, abnormal movement speed, movement keys not working as it should be.

https://www.youtube.com/watch?v=8eqK_rsU1nQ

https://www.youtube.com/watch?v=xaxR8bJrwjc

https://www.youtube.com/watch?v=GrufsiA7as8

https://www.youtube.com/watch?v=-n5lG5fFEJM
Fraps stop recording every couple seconds so I had to split the video into parts.

**Comment by SleepingTea98** [comment]
Not a bug with the modpack.

Make sure you have updated your graphics driversand don't have mods like optifine installed
