### ISSUE TITLE
Missing mod on client side when using official server files

### ISSUE THREAD

**Issue by adadagabaCZ** [SleepingTea98/Infinity-Modpack#14]
Hello, today I tried setting up a Infiniti server, but I ran into this issue:
When I launch Infiniti Server and try to log in I get an error that the mod (Woot) is missing at the client side. But when I add the mod on the client side or remove it on the server side I get "illegal client" bug. How can I fix this?
Here is console when trying logging with both sides as they come:
![errors](https://user-images.githubusercontent.com/55284872/64867210-3ca05380-d63d-11e9-8fa6-73ae738094c9.jpg)

**Comment by SleepingTea98** [comment]
Please download the new server files
