### ISSUE TITLE
Bugs/Broken

### ISSUE THREAD

**Issue by erikfvang** [SleepingTea98/Infinity-Modpack#15]
Bugs/Broken Mods on Public Server:

Electroblob's Wizardry:
Magic wands would not upgrade on the Arcane Workbench

Thaumcraft:
The frery projectile task wont complete when getting shot my fire(fireball, fire from dispenser)

Monk Mod
Unable to complete Level 19 after killing Wither with bare hand

**Comment by SleepingTea98** [comment]
We've added this to our bug tracker and looking into it
