### ISSUE TITLE
GriefPrevention: Cannot reclaim an abandoned claim.

### ISSUE THREAD

**Issue by khalongaming** [SleepingTea98/Infinity-Modpack#3]
Here are the steps to reproduce the bug on the infinity server:

1. Create a claim using golden shovel.
2. Abandon the claim just created with /abandonclaim
3. Use the golden shovel once more to try to claim the area that was previously claimed in step 1.
4. An error will output to the chat stating that the claim would overlap an existing claim.
5. Right click the ground using a stick and a message will output to chat stating that 'no one has claimed this block'

**Comment by khalongaming** [comment]
So I noticed running /version griefprevention returns the message "This server is not running any plugins."

**Comment by JakeOv** [comment]
Yes I keep running into this problem it will let you claim one corner but not the other it keeps saying its overlapping an existing one when its not.
![2019-04-11_17 34 13](https://user-images.githubusercontent.com/49537679/55994707-73360480-5c80-11e9-9e17-bdda3c1a09bd.png)
![2019-04-11_17 34 56](https://user-images.githubusercontent.com/49537679/55994710-74673180-5c80-11e9-9a9e-d74381f59083.png)

**Comment by SleepingTea98** [comment]
Thank you. We know of an issue, we're working on a fix for it
